### PR TITLE
Add facebook and mail icons to footer

### PR DESCRIPTION
**Pull request by trevorknight**
This commit adds a 'mail' and 'facebook' icon next to their
respective social links in the footer. It also fixes the
Facebook link which was not pointing to Facebook.

### CODE REVIEW

**Review by therewasaguy — APPROVED** [review]
👍

**Review by sunnythere — CHANGES_REQUESTED** [review]
Cool.  We can get rid of the "icon--github" class on the new icons.  The specific icon classes are not being used currently, but we can make them "icon--emaillist" and "icon--facebook" just for consistency.  Also, I'm not sure where this is coming from, but there seems to be a minor spacing issue with the new icons?   The old ones have a space between the icon and the text.

**Comment by sunnythere** [comment]
see spacing.... 

screen shot 2017-05-22 at 6 17 58 am

**Comment by trevorknight** [comment]
> see spacing....

Good catch.

I can't see why they are different. In all cases, the icons themselves are 16x16 but for the Twitter and Github icons, the containing span is 20.16x17 whereas for the new icons, the containing span is 16x17. No changing of the span classes seems to help.

If I add a space after the includes, like so:
`. . . {% include icon-facebook.svg %} </span> . . .`
 it comes out exactly right (20.16x17) but I don't see where that space could be coming from in the Twitter and Github icons. (Or even the 'empty' icon!)

Any ideas? I'm stumped! 


screen shot 2017-05-27 at 14 29 26
screen shot 2017-05-27 at 14 29 40

**Comment by sunnythere** [comment]
So weird.  The only difference I could discern is the xml declaration in the two new svg files... so I tried taking them out, and that created a space after the icon.  My understanding was that the declaration is optional, but I'm not sure why it would make a physical difference here.

**Review by sunnythere — APPROVED** [review]

**Review by sunnythere — APPROVED** [review]
approving changes-- we can just keep the spaces you added.  or we can take out the xml line?  either way.

**Pull request merged**
