### PR TITLE
Add FREE statment & line breaks

### PR DESCRIPTION
**Pull request by khoeger**
Add "FREE. All are welcome" to event template.
Add spaces so that this statement fits on page.

### CODE REVIEW

**Comment by khoeger** [comment]
@trevorknight , thoughts?

**Review by trevorknight — COMMENTED** [review]
Saying "FREE! All are welcome!" seems great if a little overzealous. (I don't love the all-caps...)

Using line breaks instead of margins, padding, or line-height is going to give pretty inconsistent results. 

In Chrome on my machine, there's more space between the title and the FREE line than between FREE and the next line and both feel like too much space. It's more space than anywhere else on the page so I think it looks janky and like an accident.

**Comment by trevorknight** [comment]
screen shot 2017-08-22 at 20 09 24

**Comment by trevorknight** [comment]
screen shot 2017-08-22 at 20 21 55

**Comment by khoeger** [comment]
To clarify, do you think I should just remove the statement?
Or

1. make it lowercase
2. just use normal spacing

**Comment by trevorknight** [comment]
Ya, The second two: normal case and no Br tags. Add margins to the css if
you think it's needed.

Thanks for your diligence with this!

**Comment by khoeger** [comment]
I've updated it! I think the placement looks strange on the page the way I have it, but I can't figure out where else to place the words in the template. Do  you have any ideas about where else it could go? Everywhere I've tried, the text either gets buried, or it obscures the address, or it just looks strange.

**Comment by trevorknight** [comment]
You could put it under or next to the registration link?

Also would you please remove the other br tags and add the itemprops please?

See here: http://schema.org/Event

**Comment by khoeger** [comment]
Let me know if I misinterpreted anything!

**Comment by trevorknight** [comment]
I don't see freeStatement as one of the defined properties of an [Event](http://schema.org/Event). Am I missing something?

Also why the span inside the paragraph tag?

I think you want: `itemprop="isAccessibleForFree" content="true"`

**Comment by khoeger** [comment]
You're not missing anything.

I did not understand how the Schema was related to the itemprop, and misunderstood the independent research I did regarding itemprops. I interpreted them to be user-generated tags, and made one up.

Also, it looked like when you wanted to tag text with an itemprop, it needed to be in the brackets with something like img, audio, etc., and the text examples were enclosed with <span>. I guess that's not true?

**Comment by trevorknight** [comment]
Hmmmm... Check out http://schema.org/docs/gs.html and let me know what you find! I merely perused it but it looks like it has all the answers

**Comment by khoeger** [comment]
Thank you! That's really helpful. I had no clue I was misunderstanding so much.

I think there may be other changes to make, based off of what I get when I check the schema output with this [snippet tool](https://search.google.com/structured-data/testing-tool).  

Thank you for your patience, and for being really awesome and helping me!

I'm going to work through the schema errors.

**Comment by khoeger** [comment]
I'm going to work through the schema errors.

**Comment by khoeger** [comment]
Fixed! (Or so I think)

**Review by trevorknight — APPROVED** [review]
Nice work! Thank you for your thoroughness and diligence.

**Pull request merged**
