### PR TITLE
Update image inclusion scheme

### PR DESCRIPTION
**Pull request by khoeger**
* Remame files from .JPG to .jpg - I needed to rename them completely for Github to recognize the file exetension change
* Change \ to / throughout recently written files

### CODE REVIEW

**Comment by khoeger** [comment]
Please note, I'm having git issues. My work keeps on being undone. I'd love to reset to 2d55df41ed8d625d0259969f6354f1c336ee2c92, because I put a lot of work into this, and redid it once already, but my work is always deleted once I commit the changes. 

If you know of any sources I can check, I'd be grateful! 

The situation stops me from checking out master and working on another branch.

**Comment by trevorknight** [comment]
Hmmmm, I don't understand. What do you mean your work keeps being undone? What did you do and what happens? 

You could drop the last commit with 
$ git rebase -i
and change pick to drop.

When you push to github though you'd have to
$ git push -f
because you're destroying history

**Comment by khoeger** [comment]
I'm not sure how to describe the issue in a way that's meaningful to you, as I don't have much github experience, and this is the only project I've worked on with people that uses version control (apart from one 4 years ago where I used turtle SVN). 

I can detail exactly what I did (most of it's in the commit history anyway?) but I think I'm going to just give this up as a bad job, reset to 10 days ago, and start again. This will happen on the 26th or 27th after work, unless I get pulled into family holiday plans. I'll take photos. Hopefully, it'll work? But if not, at least it will be (theoretically) easier to debug with help. 

Sorry that it was less than helpful.

**Comment by khoeger** [comment]
I shall look up rebase -i! And push -f. Thank you.

**Comment by khoeger** [comment]
I believe I've reset the branch to commit 2e6035dfe3cd19713b8535a7b229e6578d6e8ab7. I shall try to redo the work from what I've reset to tomorrow after work.

**Comment by khoeger** [comment]
I have added all the text that changed, and the images, back in. It should be merge-able. 
 
But please help me check!

**Comment by khoeger** [comment]
Hi, if possible, please let me know if this is merge-able. I'd want to try to add in December's Hackathon ASAP. And the MCL changes.

**Comment by trevorknight** [comment]
Will do

sent from my phone

**Review by trevorknight — APPROVED** [review]

**Pull request merged**
