### PR TITLE
Add submission forms for resources and projects

### PR DESCRIPTION
**Pull request by trevorknight**

### CODE REVIEW

**Comment by khoeger** [comment]
I think we need to change the title and organization of this page a bit. Perhaps call it projects, and have an obvious way of splitting up Past Projects from current projects.  Two headers? Or a submit your project Button? And then Past Projects below?

Basically, if I were coming to this page, I'd get lost trying to submit a project.

**Comment by khoeger** [comment]
About the project submission info, are we currently giving up on the technologies used list? Such as what we have here? https://docs.google.com/forms/d/e/1FAIpQLSeWkZILfwuPuY7xcSfptzvoOR9TBTiYGbTIniNOY9Xx79hwjg/viewform

Or, is this different from the event project submissions? Such as, everyone submits in one place, but if someone thinks their project is super special, they submit again here?

**Comment by trevorknight** [comment]
- OK, I change the top of the page a bit, see how you like it.

- I think asking people to fill out two submission forms is out of the question. We can edit the form that I've linked. I didn't realize "Sample Hackathon 2017" was ready for use.

- Personally I would rather have no set of checkboxes than what we have there on "Sample Hackathon 2017 Projects": they mix technologies with general categories of project and have no clear organization. What does "Technologies used: Tool" mean?

**Review by khoeger — APPROVED** [review]
Thank you!

**Pull request merged**
