### PR TITLE
Change project group listing order to by reverse date

### PR DESCRIPTION
**Pull request by khoeger**
When displayed in Immersive's localhost view, the project page looked like below, because it was in reverse alphabetical order. 
- October 2017
- December 2017
- August 2017

The groupings should now be in reverse date order, i.e.
- December 2017
- October 2017
- August 2017

### CODE REVIEW

**Review by therewasaguy — APPROVED** [review]

**Review by trevorknight — COMMENTED** [review]
Nice! Good catch. I don't know why I did this! You're right that they're in the wrong order.

This isn't working how you think it does, however.

Check out the documentation for group_by_exp: https://jekyllrb.com/docs/templates/#filters

After the group_by_exp, the output is a list of dictionaries:

[{"name"=>"Oct 14, 2017", "items"=>[#<Jekyll::Document _projects/2017-10-14-Computer-chorus.md collection=projects>, #<Jekyll::Document _projects/2017-10-14-Flappy-Beep.md collection=projects>, #<Jekyll::Document _projects/2017-10-14-Homeostatic-Harmony.md collection=projects>,  . . .

Notice just below this we iterate that collection and access the 'name' and 'items' fields. There's nothing called 'project.date' or even 'date', just 'name' and 'items'.

The good news is they're already sorted by date because that's the order they're in before grouping so we just need to reverse. You can remove the sort expression!

**Comment by khoeger** [comment]
Oops. Thanks! I definitely misunderstood the details when I read the documentation.

It's ok to squash and merge now, right?

**Review by trevorknight — APPROVED** [review]
Sounds good!

**Comment by therewasaguy** [comment]
thanks for the clarification, and sorry for my premature approval !

**Pull request merged**
