### PR TITLE
Adjust header spacing

### PR DESCRIPTION
**Pull request by sunnythere**
- adjust header logo position so it doesn't get cut off on left side.
- adjust menu position so that right side is referenced instead of left (to prevent right-side cut-off at medium screen widths)

### CODE REVIEW

**Comment by sunnythere** [comment]
re body font: changed it back (was testing it before)-- should be the same as current

**Comment by trevorknight** [comment]
Cool cool cool cool cool cool, I'm glad we're picking up momentum again on getting this website finished.

Two small comments:
- Some description for the pull request would help me understand why the changes are being made and therefore review.
- I think there's something wrong with widths, compare the screenshot at head:
screen shot 2017-05-19 at 5 27 47 pm
screen shot 2017-05-19 at 5 27 21 pm

**Comment by trevorknight** [comment]
Wait, sorry, I'm mistaken. That image was from the new-style branch.

**Comment by trevorknight** [comment]
Looks good! Thanks for your patience!

**Review by trevorknight — APPROVED** [review]

**Comment by khoeger** [comment]
This is great!

While we're on the topic of header spacing, can we add more space between the first and second lines of Monthly Music Hackathon? The M and H in Monthly and Hackathon currently form a single line, and the y in monthly intersects the h in hackathon.

I'm not sure if it's purposeful, but if it's not, I'd like to switch it!

**Comment by sunnythere** [comment]
The narrow line spacing is intentional.  But if we don't like it, I can widen it.

**Pull request merged**
