### PR TITLE
Clean up the listings of events on the site

### PR DESCRIPTION
**Pull request by trevorknight**
- Only one page, titled 'Events' for events
- Past events now at /events/archive/
- Future events now at /events/
- Can show up to three future events on home page

### CODE REVIEW

**Comment by khoeger** [comment]
This works. But what's the motive behind this change? Is it saving space in the header?

**Comment by trevorknight** [comment]
A couple reasons I guess:

- Yeah, it's visual clutter to have "past events" and "future events" both at the top level, just having 'Events' is much nicer.
- I would bet the number of people coming to the website interested in upcoming events are far greater than those interested in past events.

**Comment by trevorknight** [comment]
In the future we group the archive by year and add in the a side-bar or at the bottom or images like you've mocked up.

**Comment by khoeger** [comment]
I agree with your events thoughts. Perhaps it will be searchable by topic in the future as well.

Do you see the projects.md conflict? I am not sure of how to resolve it. I will follow this: http://weblog.masukomi.org/2008/07/12/handling-and-avoiding-conflicts-in-git/

**Comment by trevorknight** [comment]
No worries! I took a look at the conflict and fixed it. 

Basically, what that means is that two branches changed the same line or lines so someone has to look at it an manually choose what the combination should be.

**Pull request merged**
