### PR TITLE
Oct2017 branch complete

### PR DESCRIPTION
**Pull request by khoeger**
Add October 2017's event write-up.

### CODE REVIEW

**Review by trevorknight — APPROVED** [review]
Looks great! Thank you so much!!

**Comment by khoeger** [comment]
Thanks! Hey, @trevorknight , do you have any ideas about how I might fix it? 

It runs properly on localhost, but at least one picture is not showing up on http://mmhpreview.com/blog/2017-10-14-New-Musical-Instruments-2017/ (see that Kate Sicchio's picture is instead replaced by the Accessible Text, which makes for a strange reading experience).

**Comment by sunnythere** [comment]
capitalize file extension?

(um, hi ::waves::)

alice

**Comment by khoeger** [comment]
I'm more than willing to give that a try. I'll tag you both, and let's see what happens!

(Hi! Good to see you. Feel free to pop in when you'd like.)

**Comment by trevorknight** [comment]
Hi Alice! Hi Katarina!

Looks like we have at least some slashes going the wrong way:
"\assets\events\20171014\DSCF8812.JPG"

-Trevor

**Comment by trevorknight** [comment]
FWIW, I would encourage lower-case file extensions. As you've noticed, JPG
and jpg aren't equivalent on non-Windows and we already use lowercase:
https://github.com/musichackathon/mmh_jekyll/tree/master/assets/events

**Comment by sunnythere** [comment]
Agree that consistency would be better practice.  You’d just have to make sure the extensions on the pics are lowercased.  If I recall correctly, photos often get uppercase extension by default when you transfer them from a camera? That’s probably where it comes from.

sent from my phone.

**Comment by khoeger** [comment]
Ah, yes! Thank you both very much. I can get to this now.

I'll change all the picture filepaths to .jpg. And shall change the slashes to /. That's what I get when I copy filepaths using Atom. Whoops.

**Pull request merged**
