### PR TITLE
Allow post excerpt on blog page

### PR DESCRIPTION
**Pull request by trevorknight**

### CODE REVIEW

**Review by khoeger — COMMENTED** [review]
Thanks! This is great. I really hope you wrote a script.

Two things: 
- We should go through and fix capitalization/formatting of titles
- Will this work once the links change? This blog will be monthlymusichackathon.com.

Let me know if you want assistance going through the capitalization/formatting.

**Comment by trevorknight** [comment]
- Okay, if you want, you can fix capitalization/formatting of titles. I generally just left everything the same as on the current site. Once we turn on pagination and add a few posts, most everything will be off the first page and very unlikely to be seen again.

- I'm not positive what you mean. I think you're talking about the old tumblr paths. I've updated them to use the redirect_from thing now.

**Comment by khoeger** [comment]
You figured it out! It might have worked anyway - because that's what Jason's creation of redirected links  was for.

**Review by khoeger — APPROVED** [review]
I made the capitalization changes I thought were necessary. Take another look, then feel free to commit!

**Comment by trevorknight** [comment]
Looks great!

**Pull request merged**
